# Generated by Django 4.2.25 on 2025-10-25 19:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('admin', 'Administrator')], default='player', max_length=7)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exerciseid', models.AutoField(db_column='exerciseId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.OneToOneField(db_column='adminId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.OneToOneField(db_column='playerId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=12, null=True)),
                ('headshot', models.IntegerField(default=0)),
                ('counterstrafing', models.IntegerField(default=0)),
                ('spray', models.IntegerField(default=0)),
                ('reactiontime', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainerid', models.OneToOneField(db_column='trainerId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('expertise', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(blank=True, max_length=11, null=True)),
                ('priceperhour', models.DecimalField(blank=True, db_column='pricePerHour', decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'trainer',
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('requestid', models.AutoField(db_column='requestId', primary_key=True, serialize=False)),
                ('daterequested', models.DateField(db_column='dateRequested')),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_deletion_request',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('planid', models.AutoField(db_column='planId', primary_key=True, serialize=False)),
                ('creationdate', models.DateField(db_column='creationDate')),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('playerid', models.ForeignKey(blank=True, db_column='playerId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
                ('trainerid', models.ForeignKey(blank=True, db_column='trainerId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainer')),
            ],
            options={
                'db_table': 'weekly_plan',
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('requestid', models.AutoField(db_column='requestId', primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='pending', max_length=20, null=True)),
                ('playerid', models.ForeignKey(blank=True, db_column='playerId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
                ('trainerid', models.ForeignKey(blank=True, db_column='trainerId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainer')),
            ],
            options={
                'db_table': 'training_request',
            },
        ),
        migrations.CreateModel(
            name='TrainingFeedback',
            fields=[
                ('feedbackid', models.AutoField(db_column='feedbackId', primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('planid', models.ForeignKey(blank=True, db_column='planId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.weeklyplan')),
                ('playerid', models.ForeignKey(blank=True, db_column='playerId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
                ('trainerid', models.ForeignKey(blank=True, db_column='trainerId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainer')),
            ],
            options={
                'db_table': 'training_feedback',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='chosentrainer',
            field=models.ForeignKey(blank=True, db_column='chosenTrainer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainer'),
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.IntegerField(db_column='dayOfWeek')),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('exerciseid', models.ForeignKey(blank=True, db_column='exerciseId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.exercise')),
                ('planid', models.ForeignKey(db_column='planId', on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='app.weeklyplan')),
            ],
            options={
                'db_table': 'plan_item',
                'ordering': ['dayofweek'],
                'unique_together': {('planid', 'exerciseid', 'dayofweek')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseStat',
            fields=[
                ('statid', models.AutoField(db_column='statId', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('exerciseid', models.ForeignKey(db_column='exerciseId', on_delete=django.db.models.deletion.CASCADE, to='app.exercise')),
                ('playerid', models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
            options={
                'db_table': 'exercise_stat',
            },
        ),
        migrations.CreateModel(
            name='EntryTest',
            fields=[
                ('testid', models.AutoField(db_column='testId', primary_key=True, serialize=False)),
                ('datetaken', models.DateField(db_column='dateTaken')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('playerid', models.ForeignKey(db_column='playerId', on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
            options={
                'db_table': 'entry_test',
            },
        ),
        migrations.CreateModel(
            name='TrainerLanguage',
            fields=[
                ('trainerid', models.OneToOneField(db_column='trainerId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.trainer')),
                ('language', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'trainer_language',
                'unique_together': {('trainerid', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TrainerAttribute',
            fields=[
                ('trainerid', models.OneToOneField(db_column='trainerId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.trainer')),
                ('level', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'trainer_attribute',
                'unique_together': {('trainerid', 'level')},
            },
        ),
    ]
